en:
  admin: &admin
    confirm_dialog: 'You are sure?'
    dashboard:
      index:
        title: 'Dashboard'
        menu: 'Dashboard'
        download_statistics_report: 'Download Statistics Report'
        download_funding_raised_per_project_report: 'Download Funding Raised Per Project Report'
        total_users:
          title: 'Total Users'
          hint: 'Number of People Engaged on Platform'
        total_company_users:
          title: 'Total Companies/Organizations'
          hint: 'Number of Companies/Organizations Engaged on Platform'
        total_communities:
          title: 'Total Communities'
          hint: 'Number of Communities Served'
        total_projects:
          title: 'Total Projects'
          hint: 'Number of Projects on Plataform'
        total_projects_draft:
          title: 'Total Projects on Draft'
          hint: 'Number of Projects on Draft Mode'
        total_projects_online:
          title: 'Total Projects Online'
          hint: 'Number of Projects Online Now'
        total_backs:
          title: 'Total Backs'
          hint: 'Number of Backs'
        total_backers:
          title: 'Total Backers'
          hint: 'Number of Backers'
        total_backed:
          title: 'Total Backed'
          hint: 'Funding Raised'
    tags:
      index:
        menu: 'Manage Tags'
        title: 'Tags management'
        name: 'Name'
        total_projects_using: 'Total projects using'
        no_tags: 'No tags yet'
        edit: 'Edit'
        destroy: 'Destroy'
        new: 'Add new tag'
      new:
        title:
          'Add new tag'
      edit:
        title: 'Edit tag'
    press_assets:
      index:
        menu: 'Manage Press Assets'
        page_title: 'Press assets management'
        no_press_assets: 'No press assets'
        title: 'Title'
        url: 'URL'
        image: 'Image'
        edit: 'Edit'
        destroy: 'Destroy'
        new: 'Add new press asset'
      new:
        title: 'Add new press asset'
      edit:
        title: 'Edit press asset'
    projects:
      index:
        by_state: 'By state'
        between_created_at: 'Created at between'
        id: ID
        name: 'Name'
        populate_backer: 'Prepopulate backer'
        send_to_trash: "Send to TRASH"
        send_to_draft: 'Send to DRAFT!'
        send_to_soon: 'Send to SOON!'
        reject: 'Reject!'
        approve: 'Approve!'
        user_id: 'User ID'
        goal: 'Goal'
        total_backs: 'Backs'
        online_date: 'Online date'
        pledged: 'Pledged'
        recommended: 'Recommended?'
        state: 'State'
        menu: 'Manage Projects'
        title: 'Projects management'
        total_projects: 'projects'
        submit: 'filter'
        expires_at: 'Expires at'
        category: 'Category'
        order_table: 'Order table'
        order_date: 'Send date'
        order_asc: 'Goal asc'
        order_desc: 'Goal desc'
        order_created_at: 'Submission date'
        featured: 'Featured?'
    financials:
      index:
        menu: 'Financial reports'
        title: 'Finalcial reports'
        submit: 'Filter'
        by_state: 'By state'
        by_progress: By progress %
    users:
      index:
        title: "Users management"
        menu: 'Manage users'
        credits: Credits
        credits_view: "Calculated credits"
        id: ID
        key: Key
        submit: Search
        has_credits_difference: "Discrepancy in credits"
        total_backed: backed
        total_backers: backers
        total_backs: backs
        total_users: users
        total_credits: credits
        total_credits_view: "calculated credits"
        user: User
        value: Value
        provider: Provider
    backers:
      messages:
        successful:
          confirm: 'Backer confirmed!'
          pendent: 'Backer unconfirmed!'
          refund: 'Backer refunded!'
          change_reward: 'Reward changed!'
          hide: 'Backer hidden!'
          cancel: 'Backer canceled!'
          push_to_trash: 'Backer deleted!'
      index:
        push_to_trash: 'Delete backer'
        cancel: 'Cancel backer'
        refund_and_hide: 'Refund and hide'
        backer_info: 'Info of backer %{key}'
        payment_id: 'Payment ID'
        payment_method: 'Payment method'
        payment_fee: 'Payment method fee'
        payment_choice: 'Payment choice'
        payer_email: 'Payer email'
        user_email: 'Catarse user email'
        pending_to_refund: 'Pending to refund'
        created_at: 'Created at'
        title: "Backers management"
        menu: 'Manage backs'
        anonymous: Anonymous?
        confirmed: Confirmed?
        credits: "Used credits?"
        id: ID
        key: Key
        no_backers: "No backers found."
        project: Project
        refunded: Refunded?
        requested_refund: "Requested refund?"
        reward: Reward
        no_reward: "No reward"
        submit: Search
        total_backed: backed
        total_backers: backers
        total_backs: backs
        total_users: Users
        user: User
        value: Value
    statistics:
      index:
        menu: "Statistics"
        title: "Statistics"
        total_users: "Users"
        total_backs: "Backs"
        total_backers: "Backers"
        total_backed: "Backed"
        total_projects: "Projects"
        total_projects_success: "Successful"
        total_projects_online: "Online"
      projects_by_week:
        title: "Projects sent per week"
        current_period: "Last 8 weeks"
        previous_period: "Previous 8 weeks"
        last_year: "Last year"
      backers_by_week:
        title: "Backed value confirmed per week"
        current_period: "Last 8 weeks"
        previous_period: "Previous 8 weeks"
        last_year: "Last year"

  channels:
    admin:
      <<: *admin
